// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = function(app, server){
    const basepath = "/v1";
    
    require('./swagger')(app);
             
    
    require('./contact')(app, basepath);
    require('./store')(app, basepath);
    require('./user')(app, basepath);

    require('./health')(app);
};
